# Generated by Django 4.2.5 on 2023-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
