# Generated by Django 4.2.5 on 2023-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
    ]
