# Generated by Django 4.2.5 on 2023-11-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriatransaccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria Financiera', 'verbose_name_plural': 'Categorias Financieras'},
        ),
    ]
